/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fap0kz.harcosvarazslo.gui;

import com.fap0kz.harcosvarazslo.modell.Palya;
import java.util.Random;


/**
 *
 * @author neszterzsolt
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    
    private Palya palya = new Palya();
    private final int HOSSZ = palya.getHOSSZ();
    private final String HARCOS = palya.getHARCOS(), VARAZSLO = palya.getVARAZSLO(), URES = palya.getURES(), HARC = palya.getHARC();
    private String[] mezok = new String[HOSSZ];
    private int harcosHP, varazsloHP;
    private Random r = new Random();
    
    
    
    public Gui() {
        initComponents();
    }
    
    public void alaphelyzet() {
        
    }
    
    public void palyatMutat() {
        
    }
    
    public void adatotMutat() {
        
    }
    
    private void harc() {
        
    }

    private void jatekVege() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLepes = new javax.swing.JButton();
        btnUjra = new javax.swing.JButton();
        lblHarcosHP = new javax.swing.JLabel();
        lblGyoztes = new javax.swing.JLabel();
        lblVarazsloHP = new javax.swing.JLabel();
        lblMezok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLepes.setText("Lepes");
        btnLepes.setMaximumSize(new java.awt.Dimension(56, 17));
        btnLepes.setMinimumSize(new java.awt.Dimension(56, 17));
        btnLepes.setPreferredSize(new java.awt.Dimension(76, 23));
        btnLepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLepesActionPerformed(evt);
            }
        });

        btnUjra.setText("Ujra");
        btnUjra.setMaximumSize(new java.awt.Dimension(56, 17));
        btnUjra.setMinimumSize(new java.awt.Dimension(56, 17));
        btnUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjraActionPerformed(evt);
            }
        });

        lblHarcosHP.setText("Harcos");

        lblGyoztes.setText("A gyöztes:");

        lblVarazsloHP.setText("Varazslo");

        lblMezok.setText("Mezok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarcosHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVarazsloHP))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(lblMezok)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblGyoztes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblMezok)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarcosHP)
                    .addComponent(lblVarazsloHP))
                .addGap(40, 40, 40)
                .addComponent(lblGyoztes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLepesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLepesActionPerformed

    private void btnUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUjraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLepes;
    private javax.swing.JButton btnUjra;
    private javax.swing.JLabel lblGyoztes;
    private javax.swing.JLabel lblHarcosHP;
    private javax.swing.JLabel lblMezok;
    private javax.swing.JLabel lblVarazsloHP;
    // End of variables declaration//GEN-END:variables
}
